### PR TITLE
Kevin's info added in team page

### PR DESCRIPTION
**Pull request by kevinam99**

### CODE REVIEW

**Review by pranesh-n — CHANGES_REQUESTED** [review]
Hey Kev,

Please rebase your files to current branch_v3. then on the root folder, add the image and the new about us file. I will then pull this, generate the _site vide Jekyll and push

Thanks,

Pranesh

**Comment by kevinam99** [comment]
Understood. I'll get to it.

**Comment by kevinam99** [comment]
Done @pranesh-n

**Comment by kevinam99** [comment]
I must say that this project has indeed helped me learn a lot within a short span of time. I haven't used GitHub this extensively since most of my projects were personal projects. Thanks for being so patient and understanding.

**Pull request closed without merging**
